# Вспомогательные сущности
input_boolean:
  manual_presence: # Для ручного переключения присутствия
    name: "Ручное управление присутствием"
    icon: mdi:account-switch
  guest_mode_active: # Для гостевого режима
    name: "Гостевой режим активен"
    icon: mdi:account-multiple-plus

# Input_select для выбора источника температуры и основного термостата (если еще не созданы)
input_select:
  primary_thermostat:
    name: "Основной термостат"
    options:
      - climate.baxi_boiler
      # Добавьте другие термостаты, если есть
    initial: climate.baxi_boiler
    icon: mdi:radiator
  temperature_source:
    name: "Источник комнатной температуры"
    options:
      - sensor.home_average_temperature
      - sensor.sonoff_snzb_02d_temperature
      - sensor.vvo_smart_life_temperature
    initial: sensor.home_average_temperature
    icon: mdi:thermometer-lines
