# Секреты конфигурации
# Координаты дома
latitude: 55.7558
longitude: 37.6176
elevation: 156

# URL для доступа
external_url: "https://your-domain.duckdns.org:8123"
internal_url: "http://192.168.0.100:8123"
internal_ip: "192.168.0.100"

# MQTT
mqtt_username: "homeassistant"
mqtt_password: "your_secure_mqtt_password"

# Камера SONOFF
camera_ip: "192.168.0.101"
camera_username: "admin"
camera_password: "your_camera_password"
camera_auth: "Basic YWRtaW46cGFzc3dvcmQ="

# OpenTherm ESP32-C6
opentherm_ip: "192.168.0.100"
opentherm_port: 25238

# Добавьте в secrets.yaml:
icloud_username: "your@icloud.com"
icloud_password: "your_app_specific_password"
apple_tv_login: "your_apple_id"
apple_tv_credentials: "generated_credentials"
router_password: "your_router_password"
