# Этот файл предназначен для MQTT сущностей (сенсоров, бинарных сенсоров и т.д.)
# Конфигурация самого брокера MQTT (адрес, порт, логин, пароль)
# должна быть выполнена через ИНТЕРФЕЙС Home Assistant.
# (Настройки -> Устройства и службы -> Добавить интеграцию -> MQTT)

# Пример MQTT сенсора (сейчас закомментирован)
# mqtt:
#   sensor:
#     - name: "Пример MQTT Сенсора"
#       state_topic: "home/living_room/temperature"

# Пустой файл, так как все MQTT устройства (котел) уже определены
# в своих пакетах (`boiler.yaml`).
