# СЦЕНЫ
scene:
  - name: "Set Heating Comfort"
    actions:
      - service: script.smart_set_temperature
        data:
          mode: comfort
          
  - name: "Set Heating Economy"
    actions:
      - service: script.smart_set_temperature
        data:
          mode: economy
          
  - name: "Set Heating Away"
    actions:
      - service: script.smart_set_temperature
        data:
          mode: away

  - name: "Set Heating Sleep"
    actions:
      - service: script.smart_set_temperature
        data:
          mode: night 