# Автоматизации для Zigbee устройств
automation:
  - alias: "Zigbee - Low Battery Alert"
    description: "Уведомление о низком заряде батарей Zigbee устройств"
    trigger:
      # Триггер по включению бинарного сенсора, который уже содержит всю логику
      - platform: state
        entity_id: binary_sensor.low_battery_alert
        to: 'on'
    action:
      - service: script.send_climate_notification
        data:
          title: "🔋 Низкий заряд Zigbee"
          # Сообщение теперь нужно формировать по-другому, т.к. триггер не содержит информации о конкретном устройстве
          # Мы можем перечислить все устройства с низким зарядом
          message: >
            Низкий заряд у следующих устройств:
            {% set threshold = states('input_number.low_battery_threshold') | int(20) %}
            {% for state in states.group.all_battery_sensors.attributes.entity_id %}
              {% set sensor = states[state] %}
              {% if sensor.state | int(100) < threshold %}
                - {{ sensor.name }}: {{ sensor.state }}%
              {% endif %}
            {% endfor %}
            Рекомендуется замена батарей.
          mobile: true

  - alias: "Zigbee - Device Offline Alert"
    description: "Уведомление о недоступности Zigbee устройств"
    trigger:
      - platform: state
        entity_id:
          - sensor.pok005_temperature
          - sensor.vvo_smart_life_temperature
          - binary_sensor.sonoff_snzb_06p_occupancy
        to: 'unavailable'
        for: "00:30:00"
    action:
      - service: script.send_climate_notification
        data:
          title: "📡 Zigbee устройство недоступно"
          message: "{{ trigger.to_state.attributes.friendly_name }} не отвечает более 30 минут."
          priority: high # Это кастомный параметр нашего скрипта, убедимся что он поддерживается
          mobile: true

  - alias: "Zigbee - Extreme Temperature Alert POK005"
    description: "Уведомление об экстремальных температурах POK005"
    trigger:
      - platform: numeric_state
        entity_id: sensor.pok005_temperature
        below: "{{ states('input_number.extreme_cold_threshold') | int }}"
      - platform: numeric_state
        entity_id: sensor.pok005_temperature
        above: 38
    action:
      - service: script.send_climate_notification
        data:
          title: "🌡️ Экстремальная уличная температура (POK005)"
          message: "Уличная температура: {{ states('sensor.pok005_temperature') }}°C. Проверьте системы."
          priority: high
          mobile: true 